"use client";

import React, { useState } from "react";
import { TestTube, Copy, Check, Download, Sparkles, CheckCircle2 } from "lucide-react";

interface TestGeneratorProps {
  code: string;
  language: string;
}

export const TestGenerator: React.FC<TestGeneratorProps> = ({ code, language }) => {
  const [copied, setCopied] = useState(false);

  // Generate language-appropriate unit test template
  const generateUnitTests = (srcCode: string, lang: string): { framework: string; fileExt: string; testContent: string } => {
    if (lang === "python" || srcCode.includes("def ")) {
      return {
        framework: "PyTest",
        fileExt: "test_review.py",
        testContent: `import pytest
from unittest.mock import patch, MagicMock

# --- Unit Tests generated by AI Code Review Agent ---

def test_happy_path():
    """Verify normal execution behavior under standard inputs."""
    # Arrange
    test_input = "valid_sample"
    
    # Act & Assert
    # Replace with target function invocation
    assert True, "Happy path execution succeeded"

def test_boundary_and_null_inputs():
    """Verify system handles empty/null boundary edge cases gracefully."""
    with pytest.raises((ValueError, TypeError)):
        # Test zero or empty value propagation
        pass

def test_security_sanitization():
    """Verify no unexpected unhandled exceptions occur during unexpected input."""
    malicious_input = "'; DROP TABLE users; --"
    # Ensure input sanitization logic prevents query failure
    assert isinstance(malicious_input, str)
`,
      };
    } else if (lang === "cpp" || srcCode.includes("#include")) {
      return {
        framework: "GoogleTest (gtest)",
        fileExt: "test_review.cpp",
        testContent: `#include <gtest/gtest.h>
#include <string>

// --- GoogleTest suite generated by AI Code Review Agent ---

TEST(CodeReviewTest, StandardExecutionPath) {
    // Arrange & Act
    std::string testInput = "Sample Test Input";
    
    // Assert
    EXPECT_FALSE(testInput.empty());
}

TEST(CodeReviewTest, MemoryAndBufferBounds) {
    // Test boundary conditions to ensure zero memory leak or buffer overflow
    std::string maxString(1024, 'A');
    EXPECT_EQ(maxString.length(), 1024);
}

int main(int argc, char **argv) {
    ::testing::InitGoogleTest(&argc, argv);
    return RUN_ALL_TESTS();
}`,
      };
    } else {
      // Default JS/TS Jest/Vitest
      return {
        framework: "Jest / Vitest",
        fileExt: "review.test.js",
        testContent: `import { describe, it, expect, beforeEach } from 'vitest';

// --- Automated Unit Test Suite generated by AI Code Review Agent ---

describe('AI Reviewed Code Test Suite', () => {

  it('should process standard valid inputs correctly', () => {
    // Test standard input parameters
    const mockItems = [
      { price: 10, quantity: 2 },
      { price: 5, quantity: 1 }
    ];
    
    expect(mockItems).toHaveLength(2);
    expect(mockItems[0].price * mockItems[0].quantity).toBe(20);
  });

  it('should handle empty or missing array parameters without crashing', () => {
    const emptyItems = [];
    expect(emptyItems.length).toBe(0);
  });

  it('should apply valid discount codes safely', () => {
    const total = 100;
    const discount = 20;
    const finalPrice = Math.max(0, total - discount);
    
    expect(finalPrice).toBe(80);
    expect(finalPrice).toBeGreaterThanOrEqual(0);
  });

});
`,
      };
    }
  };

  const { framework, fileExt, testContent } = generateUnitTests(code, language);

  const handleCopy = () => {
    navigator.clipboard.writeText(testContent);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = () => {
    const element = document.createElement("a");
    const file = new Blob([testContent], { type: "text/plain" });
    element.href = URL.createObjectURL(file);
    element.download = fileExt;
    document.body.appendChild(element);
    element.click();
    document.body.removeChild(element);
  };

  return (
    <div className="rounded-2xl border border-slate-800 bg-slate-900/90 p-5 shadow-xl backdrop-blur-md">
      
      {/* Header */}
      <div className="flex flex-wrap items-center justify-between gap-3 border-b border-slate-800 pb-4 mb-4">
        <div className="flex items-center space-x-2">
          <TestTube className="h-5 w-5 text-indigo-400" />
          <h3 className="text-sm font-bold text-slate-200">
            Generated Unit Test Suite
          </h3>
          <span className="rounded-full bg-indigo-500/10 px-2.5 py-0.5 text-xs font-semibold text-indigo-400 border border-indigo-500/20">
            {framework}
          </span>
        </div>

        <div className="flex items-center space-x-2">
          <button
            onClick={handleCopy}
            className="flex items-center space-x-1.5 rounded-lg bg-slate-800 px-3 py-1.5 text-xs font-medium text-slate-300 hover:bg-slate-700 hover:text-white transition border border-slate-700"
          >
            {copied ? <Check className="h-3.5 w-3.5 text-emerald-400" /> : <Copy className="h-3.5 w-3.5 text-slate-400" />}
            <span>Copy Test Code</span>
          </button>

          <button
            onClick={handleDownload}
            className="flex items-center space-x-1.5 rounded-lg bg-indigo-950/80 px-3.5 py-1.5 text-xs font-semibold text-indigo-300 hover:bg-indigo-900 hover:text-white transition border border-indigo-800/60 shadow-md"
          >
            <Download className="h-3.5 w-3.5 text-indigo-400" />
            <span>Download {fileExt}</span>
          </button>
        </div>
      </div>

      {/* Code Display */}
      <div className="relative rounded-xl border border-slate-800 bg-slate-950/80 p-4 font-mono text-xs text-indigo-200 overflow-x-auto max-h-96 leading-relaxed whitespace-pre">
        {testContent}
      </div>

    </div>
  );
};
